-- ============================================
-- PostgreSQL Schema for Social Media Intelligence
-- ============================================
-- Note: UUIDs are generated by the application (JPA)
-- ============================================

-- ============================================
-- Table: users
-- ============================================
CREATE TABLE users
(
    id         UUID PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    full_name  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);

-- Index on email for query performance
CREATE UNIQUE INDEX idx_user_email ON users (email);

-- ============================================
-- Table: user_credentials
-- ============================================
CREATE TABLE user_credentials
(
    id            UUID PRIMARY KEY,
    password_hash TEXT      NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,

    -- Foreign key constraint
    CONSTRAINT fk_user_credentials_user
        FOREIGN KEY (id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

-- ============================================
-- Trigger: Auto-update updated_at timestamp
-- ============================================

-- Function to update updated_at column
CREATE
    OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at
        = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$
    LANGUAGE plpgsql;

-- Trigger for users table
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE
    ON users
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Trigger for user_credentials table
CREATE TRIGGER update_user_credentials_updated_at
    BEFORE UPDATE
    ON user_credentials
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
